---
-  hosts: nfs_server
   become: true
   tasks:

   - name: install httpd
     yum:
       name: httpd
       state: latest
   - name: ensure apache is running
     service:
      name: httpd
      state: started


- name: Firewalld Rules
  hosts: nfs_server
  become: true

  tasks:
  - name: Web acces Firewall rule
    firewalld:
       zone: public
       port: 8081/tcp
       permanent: yes
       state: enabled

  - name: Reload firewalld service
    service: 
      name: firewalld
      state: restarted
