---
-  hosts: all
   become: true
   tasks:

   - name: install httpd
     yum:
       name: httpd
       state: latest
   - name: ensure apache is running
     service:
      name: httpd
      state: started

   - name: "Tasks2: Enabling the port on firewall"
     become: true
     firewalld:
      port: 8081
      permanent: true
      state: enabled
      immidiate: yes
